name: Build and Deploy Jekyll Site

on:
  push:
    branches: [main]  # 每次推送 main 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: myblog

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保包含所有历史记录，用于部署

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: myblog/_site
          publish_branch: gh-pages
          force_orphan: true  # 清空旧内容，保留纯净静态页
